config/routes.rb
InitialRelease::Application.routes.draw do

  match "asked" => "ask#new", :as => 'asked'

  root :to => 'homes#index'

	match "/cms/articles/index" => "cms/articles#index", :as=>'cms_article_index'
	match "/cms/articles/show/" => "cms/articles#show", :as=>'cms_article_show'
	match "/cms/articles/update" => "cms/articles#update", :as=>'cms_article_update'
	match "/cms/articles/new/(:parent_id)" => "cms/articles#new", :as=>'cms_article_new'
	match "/cms/articles/add" => "cms/articles#add", :as=>'cms_article_add'
	match "/cms/articles/rem" => "cms/articles#rem", :as=>'cms_article_rem'

	match "/cms/articles/:id/edit" => "cms/articles#edit"#, :as=>'cms_article_rem'

	match "/news" => "homes#list", :as=>'news'
	match "/news/:id" => "homes#index", :as=> 'new_show'

	match "/cms/users/update" => "cms/users#update", :as=>'user'

  match "/admin" => "homes#enter", :constraints => { :host => /localhost/ }

  match "/contact" => "homes#index", :id=>'2' , :as=>'contact'
  match "/price" => "homes#index", :id=>'3' , :as=>'price'
  match "/ror_book" => "homes#book", :as => 'book'
  match "/ror_book/article/:id" => "homes#index", :as=> 'book_show'

  match 'notready' => 'homes#notready'
  match 'price' => 'homes#price'

	match 'add' => 'questions#add' , :as => 'add_question'
  match 'rem/:id' => 'questions#rem', :as=>'rem_question'
  match 'answer/:id' => 'questions#answer', :as=>'answer_question'
  match 'question/:num' => 'questions#index', :as => 'index_questions'

  match 'enter' => 'homes#enter', :as => 'enter'
  post 'autoriz' => 'homes#autoriz', :as => 'autoriz'
  match 'exit' => 'homes#exit', :as => 'exit'

end

app/models/question.rb
class Question < ActiveRecord::Base
	has_one :answer
	
	cattr_reader :per_page
  @@per_page = 3
end

class Answer < ActiveRecord::Base
	belongs_to :question
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  layout 'my'

  def index
    #@questions = Question.all
		#@questions = Question.paginate :page => params[:page], :order => 'created_at DESC'
		#if @questions == nil
		@questions = Question.all
		@question = Question.new
  end

	def add
		if params[:question].present?
			@question = Question.new(params[:question])
			@text = @question.body
			if !@text.strip.empty?
				if Question.all == [] or Question.last.body != @question.body
					#@text
					@question.body = @text.gsub("<", "&alt").gsub(">", "&alt").gsub("\r\n", "<br />")
					@question.save
					Sender.salt_question(@question.autor, @question.body).deliver
				end
			end
		end

		@questions = Question.all
		respond_to do |format|
    	format.js {render :layout=>false}
		end
		#format.js { render :layout => false }
		#if params[:body].present?
		#	@questions = Question.all
		#end
	end

	def rem
		@question = Question.find(params[:id])
		@question.destroy
		@questions = Question.all
	end

	def answer
		@question = Question.find(params[:id])
		Answer.new do |a|
			a.body = params[:answer][:body].gsub("\r\n", "<br />")
			@question.answer = a
			@question.save
		end
		@questions = Question.all
	end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :reply %><br />
    <%= f.text_area :reply %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_questionlist.html.haml
- @questions.each do |q|
	%table.question{:align=>"center", :width=>"100%", :cellpadding=>"0", :cellspacing=>"0"}
		%tr
			%td.autor{:align=>"left", :width=>80}
				- if q.autor == ''
					%span.name Аноним
				- else
					%span.name= q.autor
			%td.autor{:align=>"right", :width=>20}
				%span.date= q.created_at.strftime("%d.%m.%y %H:%M")
		%tr
			%td.body{:align=>"left", :colspan=>"2"}!= q.body
		- if session[:user_id].present?
			%tr
				%td
					= link_to( "удалить", rem_question_path(q.id, :format => :js), :remote => "true" )
				%td
					- form_for :answer, :remote => true, :url => answer_question_path(q.id) do |f|
						= f.text_area :body, :width=>"300px", :height=>"8"
						= f.submit 'ответить'
					- link_to( "answer", answer_question_path(q.id, :format => :js), :remote => "true" )
		- if q.answer!=nil
			%tr
				%td{ :colspan=>"2" }
					%p.answer
						!= q.answer.body
	%br/

app/views/questions/add.js.erb
$("#questlist").html("<%= escape_javascript(
render(:partial => "questionlist")) %>");

app/views/questions/answer.js.erb
$("#questlist").html("<%= escape_javascript(
render(:partial => "questionlist")) %>");

app/views/questions/index.html.haml
.entry
	%h1 Вопрос-ответ
	%p
		В данном разделе
		= link_to('сайта', { :controller => 'homes', :action => 'index' }, :class => 'active')
		можно задать интересующий Вас вопрос и получить исчерпывающий ответ.
	%br/
	#questlist
		= render(:partial=>"questionlist")
		=# will_paginate @questions
	%br/
	- form_for :question, :remote => true, :url => add_question_path do |f|
		= f.label 'Ваше имя:'
		= f.text_field :autor, :class=>'styled', :value=>''
		= f.label 'Текст вопроса:'
		= f.text_area :body, :class=>'styled', :id=>'messageText'
		%br/
		= f.submit :value=>'Отправить', :style=>"font-size: 10px;", :id=>'submitButton'
		%i{ :style=>"margin-left: 5px;" } Ctrl + Enter

app/views/questions/rem.js.erb
$("#questlist").html("<%= escape_javascript(
render(:partial => "questionlist")) %>");