config/routes.rb
InitialRelease::Application.routes.draw do

  match "asked" => "ask#new", :as => 'asked'

  root :to => 'homes#index'

	match "/cms/articles/index" => "cms/articles#index", :as=>'cms_article_index'
	match "/cms/articles/show/" => "cms/articles#show", :as=>'cms_article_show'
	match "/cms/articles/update" => "cms/articles#update", :as=>'cms_article_update'
	match "/cms/articles/new/(:parent_id)" => "cms/articles#new", :as=>'cms_article_new'
	match "/cms/articles/add" => "cms/articles#add", :as=>'cms_article_add'
	match "/cms/articles/rem" => "cms/articles#rem", :as=>'cms_article_rem'

	match "/cms/articles/:id/edit" => "cms/articles#edit"#, :as=>'cms_article_rem'

	match "/news" => "homes#list", :as=>'news'
	match "/news/:id" => "homes#index", :as=> 'new_show'

	match "/cms/users/update" => "cms/users#update", :as=>'user'

  match "/admin" => "homes#enter", :constraints => { :host => /localhost/ }

  match "/contact" => "homes#index", :id=>'2' , :as=>'contact'
  match "/price" => "homes#index", :id=>'3' , :as=>'price'
  match "/ror_book" => "homes#book", :as => 'book'
  match "/ror_book/article/:id" => "homes#index", :as=> 'book_show'

  match 'notready' => 'homes#notready'
  match 'price' => 'homes#price'

	match 'add' => 'questions#add' , :as => 'add_question'
  match 'rem/:id' => 'questions#rem', :as=>'rem_question'
  match 'answer/:id' => 'questions#answer', :as=>'answer_question'
  match 'question/:num' => 'questions#index', :as => 'index_questions'

  match 'enter' => 'homes#enter', :as => 'enter'
  post 'autoriz' => 'homes#autoriz', :as => 'autoriz'
  match 'exit' => 'homes#exit', :as => 'exit'

end

app/controllers/homes_controller.rb
#encoding: utf-8
class HomesController < ApplicationController
	layout :user_layout #'my'

	#def initialize
	#	@curent_page = 'home'
	#end

	def index
		if !params[:id].present?
			@article = Article.first
		else
			begin
				@article = Article.find(params[:id]) || nil
			  @article
			rescue => ex
				redirect_to notready_path
			end
		end
		#@text = "мой текст"
		#flash[:cur_page] = 'index'
		#File.open("marshalled.txt", "w") { |file| Marshal.dump(params.inspect, file) }
  end

  def book
    flash.now[:notice] = 'Перевод книги "Practical Rails Social Networking Sites, Apress (2007)"'
    #flash[:notice] = { 'Текстовое сообщение', :level=>:notice }
    @articles = Article.where(:parent_id => 8)
  end

  def list
  	@articles = Article.find(:all, :conditions => ["id!=1 and id!=2 and id!=3 and parent_id is NULL"], :order => "created_at DESC")
  end

  def notready
  end

  def price
  end

  def enter
  end

  def autoriz
  	if params[:user][:name].blank?
  		flash[:notice] = 'имя не должно быть пустым'
  		redirect_to :back
  	elsif params[:user][:pass].blank?
  		flash[:notice] = 'пароль не должен быть пустым'
  		redirect_to :back
  	else
  		@u = User.find_by_name(params[:user][:name])
  		if @u == nil
	  		redirect_to :back
	  		flash[:notice] = 'не найден пользователь с заданным сочетанием пароля и имени'
  		elsif @u.pass != params[:user][:pass]
  			redirect_to :back
	  		flash[:notice] = 'не найден пользователь с заданным сочетанием пароля и имени'
  		else
  			session[:user_id] = @u.id
  			redirect_to (:controller => 'cms/articles', :action=>'index')
  		end
  	end
  end

  def exit
  	session[:user_id] = nil
  	redirect_to(:action=>'index')
  end

  protected
		def user_layout
			if current_user == nil
			  "my"
			elsif !current_user.admin?
			  "my"
			else
			  "admin"
			end
		end

end

app/helpers/homes_helper.rb
#encoding: utf-8
module HomesHelper
	def body_for_news(body)
		pattern = /(^.*<\/p>)/ #/(^<h3><\/p>)/;\W*\w*\d*\S*\s*\D*		
		pattern =~ body
		data = Regexp.last_match(1)
		
		if data != nil
			return data
		else
			return body
		end		
	end
end

app/views/homes/blog.html.haml
= render(:partial => "shared/my_blog_link", :locals => {text:@text, date:'февраля 28, 2010'})
	.floater
		%h1
			%a Привет, мир and YOU!
			.descr февраля 28, 2010

app/views/homes/book.html.haml
%h1 Practical Rails Social Networking Sites
%h2 Rails. Практика по созданию социальной сети
%br/
%p Нашел недавно очень занимательную книгу, описывающую детальное создание сайта так называемой социальной сети на Ruby on Rails. Хоть и написана была достаточно давно, но ничего даже отдаленно похожего у русских писателей-программистов я пока не находил. Поэтому и решил сделать свой, пусть и не профессиональный, но надеюсь близкий к таковому, перевод данного великолепнейшего труда.
%p 
	Перевод буду делать постепенно, выкладывая главы и разделы по мере поступления свободного времени
	= image_tag "/images/book/smile.png", :style => 'padding:0;margin:0;border:none;display:inline;'
%ul
	- @articles.each do |article|
		%li{:style=>'margin-top:10px;'}= link_to article.title, book_show_path(article), :style => 'display:block;padding:0;margin:0;text-decoration:none;'

app/views/homes/enter.html.haml
- form_for :user, :url => autoriz_path do |f|
	= f.label 'Ваше имя:'
	= f.text_field :name, :class=>'styled', :value=>''
	= f.label 'Пароль:'
	= f.password_field :pass, :class=>'styled'
	%br/
	= f.submit :value=>'Отправить', :style=>"font-size: 10px;"
	- if flash[:notice]
		%p.info= flash[:notice]

app/views/homes/index.html.haml
.entry	
	= link_to 'оглавление', book_path if @article.parent_id && @article.parent_id==8
	%h1= @article.title
	%br/
	!= @article.body
- if @article.info != ''
	%p.info 
		!= @article.info
	-# title("page_title")

app/views/homes/list.html.haml
.entry	
	%h1 Блог
	%br/
	- @articles.each do |article|
		%h3= article.title
		%br/
		!= body_for_news(article.body)
		= link_to 'дальше...', new_show_path(article.id), :style=>'font-weight: bold;'
		%br/
		%br/

app/views/homes/notready.html.haml
.entry	
	%h1 К сожалению, запрашиваемая страница еще не готова. В самое ближайшее время я ее подготовлю и будет всем радость :)

app/views/homes/price.html.haml
.entry	
	%h1 Цены
	%br/
	%p Для каждого сайта стоимость разработки определяется индивидуально, но какая-то определенность необходима любому из нас, поэтому далее приводятся примерные расценки, дабы заранее можно было расчитать функционал сайта исходя из бюджета который планируется на него затратить.
	%h3 1. Сайт стандартный от 5 000 руб.
	%ul
		%li современный дизайн;
		%li текстовые разделы;
		%li каталог товаров.
	%br/
	%h3 2. Интернет-магазин от 20 000 руб.
	%ul
		%li современный дизайн;
		%li система администрирования сайта;
		%li текстовые разделы;
		%li каталог товаров, с возможностью заказа товаров;
		%li корзина покупателя.
	%br/
	%h3 3. Корпоративный сайт от 30 000 руб.
	%ul
		%li современный дизайн;
		%li система администрирования сайта;
		%li текстовые разделы;
		%li каталог товаров; 
		%li объединение с программами предприятия (1С, Excel)
		%li фотогаллерея
		%li новости.
	%p 
		При заказе сайта предоставляется
		%strong бесплатная 
		помощь в подборе и регистрации домена и хостинга для сайта.
	%p
		Поддержание сайта в актуальном, рабочем состоянии, обновление его элементов, добавление новой функциональности, а также продвижение сайта в поисковых системах, все это 
		%strong жизненно 
		необходимо, если сайт разрабатывается не на месяц-два, а как минимум на год. Можно, конечно, своими силами выполнять те или иные задачи по жизнеобеспечиванию сайта, но лучше доверить это дело профессионалам. 
		= link_to('Юлиансайт', { :controller => 'homes', :action => 'index' }, :class => 'active')
		готов предоставить 
		%strong полный
		спектр услуг за умереную плату, для того, чтобы сайт радовал глаз клиентов и Ваш кошелек.
	%p.info
		Цена определяет качество