config/routes.rb
InitialRelease::Application.routes.draw do

  match "asked" => "ask#new", :as => 'asked'

  root :to => 'homes#index'

	match "/cms/articles/index" => "cms/articles#index", :as=>'cms_article_index'
	match "/cms/articles/show/" => "cms/articles#show", :as=>'cms_article_show'
	match "/cms/articles/update" => "cms/articles#update", :as=>'cms_article_update'
	match "/cms/articles/new/(:parent_id)" => "cms/articles#new", :as=>'cms_article_new'
	match "/cms/articles/add" => "cms/articles#add", :as=>'cms_article_add'
	match "/cms/articles/rem" => "cms/articles#rem", :as=>'cms_article_rem'

	match "/cms/articles/:id/edit" => "cms/articles#edit"#, :as=>'cms_article_rem'

	match "/news" => "homes#list", :as=>'news'
	match "/news/:id" => "homes#index", :as=> 'new_show'

	match "/cms/users/update" => "cms/users#update", :as=>'user'

  match "/admin" => "homes#enter", :constraints => { :host => /localhost/ }

  match "/contact" => "homes#index", :id=>'2' , :as=>'contact'
  match "/price" => "homes#index", :id=>'3' , :as=>'price'
  match "/ror_book" => "homes#book", :as => 'book'
  match "/ror_book/article/:id" => "homes#index", :as=> 'book_show'

  match 'notready' => 'homes#notready'
  match 'price' => 'homes#price'

	match 'add' => 'questions#add' , :as => 'add_question'
  match 'rem/:id' => 'questions#rem', :as=>'rem_question'
  match 'answer/:id' => 'questions#answer', :as=>'answer_question'
  match 'question/:num' => 'questions#index', :as => 'index_questions'

  match 'enter' => 'homes#enter', :as => 'enter'
  post 'autoriz' => 'homes#autoriz', :as => 'autoriz'
  match 'exit' => 'homes#exit', :as => 'exit'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/cms/application_controller.rb
class ApplicationController < ActionController::Base  	
end

app/controllers/cms/articles_controller.rb
#encoding: utf-8
class Cms::ArticlesController < ApplicationController
  layout 'admin'
  
  before_filter :have_access
  
  def edit
    @article = Article.find(params[:id])
  end 
  	  	
  def index
  	@articles = Article.all
  	@article = Article.new
  end
  
  def show
  	@id = params[:num_article]
  	@article = Article.find(@id)
  	respond_to do |format|
    	format.js {render :layout=>false}
    end    
  end
  
  def update
  	@id = params[:article][:id]
  	@article = Article.find(@id) 		
 		if !@article.update_attributes(params[:article])
			@message = "Ошибка при сохранении"
		else
			@message = "Запись успешно сохранена"
		end
		
		respond_to do |format|
    	format.js {render :layout=>false}
    	format.html { redirect_to :action=>'index' }
    end   
  end
  
  def rem
  	@id = params[:article][:id]
  	@article = Article.find(@id)
  	if !@article.destroy
			@message = "Ошибка при удалении"
		else
			@message = "Запись успешно удалена"
		end
  	respond_to do |format|
    	format.js {render :layout=>false}
    end    
  end
  
  def new
  	@article = Article.new
  	@article.parent_id = params[:parent_id] if params[:parent_id]
  	
  	respond_to do |format|
    	format.js {render :layout=>false}
    end   
  end
  
  def add
  	@last = Article.last.id
  	@article = Article.new(params[:article])
 		
 		if !@article.save
			@message = "Ошибка при сохранении"
		else
			@message = "Запись успешно сохранена"
		end
				
		respond_to do |format|
    	format.js {render :layout=>false}
    end    
  end
  
  protected
  	def have_access
			if current_user == nil
				redirect_to enter_path
			end
  	end
end

app/controllers/cms/users_controller.rb
#encoding: utf-8
class Cms::UsersController < ApplicationController
  layout 'admin'
  
  before_filter :have_access
  
  protected
  	def have_access
			if current_user == nil
				redirect_to enter_path
			end
  	end
	
	def update
		@id = params[:user][:id]
		@user = User.find(@id)
		@user.update_attributes(params[:user]) ? render(:update) : redirect_to(:root)
	end
end

app/views/cms/articles/_article.html.haml
%td{ :width=>'100px' }
	= truncate(article.title, :length=>15, :omission=>'...')
	.content{ :id=>"title#{article.id}" }= article.title
%td
	= truncate(article.body, :length=>50, :omission=>'...')
	.content{ :id=>"body#{article.id}" }= article.body
%td{ :width=>'150px' }
	= truncate(article.info, :length=>20, :omission=>'...')
	.content{ :id=>"info#{article.id}" }= article.info

app/views/cms/articles/_edit.html.erb
<% form_for(@article, :remote=>'true', :url => { :controller=>'cms/articles', :action=>'update' }) do |f| %>
	<%= f.hidden_field :id %>
	<%= f.hidden_field :parent_id %>
	<table id='editTable'>
		<tr>
			<td>
				<div class='titleText'>Заголовок</div>
			</td>
			<td>
				<div id='inputTitle'><%= f.text_field :title %></div>
			</td>
		</tr>			
		<tr>
			<td>
				<div class='titleText area'>Содержание</div>
			</td>
			<td>
				<div id='inputBody'><%= f.cktext_area :body, :toolbar=>'Easy', :width=>'100%', :height=>'200px' %></div>
			</td>
		</tr>
		<tr>
			<td>
				<div class='titleText'>Цитата</div>
			</td>
			<td>
				<div id='inputInfo'><%= f.text_field :info %></div>
			</td>
		</tr>
		<tr>
			<td></td>
			<td><div><%= f.submit :id=>'but', :value=>'сохранить' %></div></td>
		</tr>
	</table>
<% end %>

app/views/cms/articles/add.js.erb
$('#editInfo').html("<%= @message %>");
$('#editInfo').fadeIn(1000).fadeOut(1000);
<% if @article != nil && @article.id != nil %>
$("<tr id='<%= @article.id %>' class=''><%= escape_javascript(
render :partial => 'article', :locals=>{ :article => @article } ) %></tr>").insertAfter("#<%= @last %>")
<% end %>
$(".striping tr").mousedown(function() {
		$(this).removeClass("over");
		$('.striping tr').removeClass('current');
		$(this).addClass("current");
	});
	$(".striping tr").mouseover(function() {
		$(this).addClass("over");	
	});
	$(".striping tr").mouseout(function() {
		$(this).removeClass("over");	
	});
	
	$(".striping tr").click(function() {
		var id = $(this).attr("id");
		$("#artNum").html("<input id='article_id' name='num_article' size='30' type='text' value='"+id+"'/>");
		$("#subNum").click();
		$('#f hr').next().animate({opacity: 'show', height:'show'}, 'slow');			
	});

app/views/cms/articles/edit.html.haml
- form_for(@article, :url => { :controller=>'cms/articles', :action=>'update' }) do |f|
	= f.hidden_field :id, :value=>@article.id
	= f.text_area(:body, :cols=>120, :rows=>25)
	= f.submit 'сохранить'

app/views/cms/articles/index.html.haml
#dialog{ :title=>'Внимание' }
	%p Действительно хотите удалить?

#hideShow
	- form_for(@articles.first, :url=>cms_article_show_path, :remote=>'true' ) do |f|
		#artNum
			= f.text_field :id
		= f.submit( :id=>'subNum' )
			
#editInfo
	информация

#showInfo
	#panelButtons
		=# %a#newArticle.editButtons{ href:'/' }
		=#	Добавить статью
		= link_to('Добавить статью', cms_article_new_path, :remote=>'true', :id=>'newArticle', :class=>'editButtons')
		= link_to('Удалить статью', cms_article_index_path, :id=>'remArticle', :class=>'editButtons')
		= link_to('Добавить в книгу', cms_article_new_path(:parent_id=>8), :remote=>'true', :id=>'newArticle', :class=>'editButtons')
	%table.striping{:width=>'100%'}
		- @articles.each do |art|
			%tr{ :id=>art.id }
				= render :partial=>'article', :locals=>{ :article=>art }
#f
	%hr/
	#editForm
		= render( :partial=>'edit', :locals => { :article=>Article.new } )

app/views/cms/articles/new.js.erb
$("#editForm").html("<%= escape_javascript(
render :partial=>'edit', :locals=>{ :article=>@article } ) %>");
$('#f hr').next().animate({opacity: 'show', height:'show'}, 'slow');
$('div#editForm form').submit(function() {		
		$('div#editForm form').attr('method', 'post').attr('action', '/cms/articles/add');
		$('.striping tr').removeClass('current');
		$('#f hr').next().animate({opacity: 'hide', height:'hide'}, 'slow');	
	});

app/views/cms/articles/rem.js.erb
$('#editInfo').html("<%= @message %>");
$('#editInfo').fadeIn(1000).fadeOut(1000);
$("#<%= @article.id %>").remove();

app/views/cms/articles/show.js.erb
$("#editForm").html("<%= escape_javascript(
render :partial=>'edit', :locals=>{ :article=>@article } ) %>");
$('#f hr').next().animate({opacity: 'show', height:'show'}, 'slow');		
$('div#editForm form').submit(function() {		
		$('.striping tr').removeClass('current');
		$('#f hr').next().animate({opacity: 'hide', height:'hide'}, 'slow');	
	});

app/views/cms/articles/update.js.erb
$('#editInfo').html("<%= @message %>");
$('#editInfo').fadeIn(1000).fadeOut(1000);
$("#<%= @article.id %>").html("<%= escape_javascript(
render :partial=>'article', :locals=>{ :article=>@article } ) %>");