config/routes.rb
InitialRelease::Application.routes.draw do

  match "asked" => "ask#new", :as => 'asked'

  root :to => 'homes#index'

	match "/cms/articles/index" => "cms/articles#index", :as=>'cms_article_index'
	match "/cms/articles/show/" => "cms/articles#show", :as=>'cms_article_show'
	match "/cms/articles/update" => "cms/articles#update", :as=>'cms_article_update'
	match "/cms/articles/new/(:parent_id)" => "cms/articles#new", :as=>'cms_article_new'
	match "/cms/articles/add" => "cms/articles#add", :as=>'cms_article_add'
	match "/cms/articles/rem" => "cms/articles#rem", :as=>'cms_article_rem'

	match "/cms/articles/:id/edit" => "cms/articles#edit"#, :as=>'cms_article_rem'

	match "/news" => "homes#list", :as=>'news'
	match "/news/:id" => "homes#index", :as=> 'new_show'

	match "/cms/users/update" => "cms/users#update", :as=>'user'

  match "/admin" => "homes#enter", :constraints => { :host => /localhost/ }

  match "/contact" => "homes#index", :id=>'2' , :as=>'contact'
  match "/price" => "homes#index", :id=>'3' , :as=>'price'
  match "/ror_book" => "homes#book", :as => 'book'
  match "/ror_book/article/:id" => "homes#index", :as=> 'book_show'

  match 'notready' => 'homes#notready'
  match 'price' => 'homes#price'

	match 'add' => 'questions#add' , :as => 'add_question'
  match 'rem/:id' => 'questions#rem', :as=>'rem_question'
  match 'answer/:id' => 'questions#answer', :as=>'answer_question'
  match 'question/:num' => 'questions#index', :as => 'index_questions'

  match 'enter' => 'homes#enter', :as => 'enter'
  post 'autoriz' => 'homes#autoriz', :as => 'autoriz'
  match 'exit' => 'homes#exit', :as => 'exit'

end

app/views/layouts/admin.html.haml
!!!
%html
	%head
		%title
			Shoppery -
			= yield(:title) || "The Place to Buy Stuff"
		= javascript_include_tag :defaults, :ckeditor, "cms.js", "jquery-ui-1.8.13.custom", "ckeditor/config.js"
		= stylesheet_link_tag "reset.css", "ie.css", "screen.css", "scaffold.css", "print.css", "cms.css", "jquery-ui-1.8.13.custom.css", "../javascripts/ckeditor/contents.css"
%body
	- if admin?
		= link_to "articles", cms_article_index_path
		- form_for :user, current_user, :url => user_path, :html => { :multipart => true } do |form|
			= form.hidden_field :id
			= form.text_field :name
			= form.file_field :avatar
			= form.submit
	.sidenav#sidebar
		- if current_user != nil
			= image_tag current_user.avatar.url
			%b=# current_user.full_name
			= link_to('выйти', exit_path)
			-# for mail in Mail.find(:all)
				.mails
					= check_box_tag "user[mail_id][]", mail.id, current_user.mails.include?(mail)
					= mail.mail
	= yield	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InitialRelease</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/my.html.haml
!!!
%html
	%head
		%title www.юлиансайт.рф. Разработка сайтов в Воронеже. Создание сайта в Воронеже. Раскрутка сайта в Воронеже, сайт веб студии
		%meta{:name=>"keywords", :content=>"Воронеж создание сайтов создать воронеже разработка реклама интернет создать сайт раскрутка"}
		%meta{:name=>"description", :content=>"Создание сайтов в Воронеже. Поддержка сайтов. Продвижение сайтов. Раскрутка сайтов. Создать сайт в Воронеже."}
		= stylesheet_link_tag "ie.css", "screen.css", "print.css", "../javascripts/fancybox/jquery.fancybox.css", "style.css"
		= javascript_include_tag :defaults, "fancybox/jquery.fancybox.pack.js", "script", "message_send"
		= include_gritter
		= csrf_meta_tag
	%body
		= gritter_flash_messages
		%div{:style=>'display:none;'}
			%script{:type=>'text/javascript'}
				(function(w,c) { (w[c]=w[c]||[]).push(function(){ try { w.yaCounter11331550=new Ya.Metrika({id:11331550, enableAll:true}); } catch(e) {} }); })(window, "yandex_metrika_callbacks");
		%script{:src=>"//mc.yandex.ru/metrika/watch.js", :type=>"text/javascript", :defer=>"defer"}
		%noscript
			%div
				%img{:src=>"mc.yandex.ru/watch/11331550", :style=>"position:absolute;left:-9999px;", :alt=>""}
		.logo
			= link_to_home("Разработка сайтов")
			= link_to("ОТПРАВИТЬ ЗАЯВКУ", asked_path, :class=>'feedback fancybox fancybox.ajax"', :id=>'send-question')
		.top
			.header
				.left
		.container
			.navigation
				= link_to_home("Главная")
				= link_to('Контакты', contact_path, :class => 'active')
				= link_to('Цены', price_path, :class => 'active')
				= link_to('Вопрос-ответ', index_questions_path(1), :class => 'active')
				= link_to('Статьи', news_path, :class => 'active')
				= link_to('RoR для создания социальной сети', book_path, :class => 'active')
			.main
				.content
					.post#post-1
						- if @article && @article.parent_id && @article.parent_id==8
							#book= yield
						- else
							= yield
					%p{:style=>"text-align:center"}
				.sidenav#sidebar
					- if current_user != nil
						%b= current_user.name
						= link_to('выйти', exit_path)
					%h2 Категории
					%ul
						%li.cat-item.cat-item-1
							= link_to_home("Главная")
							= link_to('Контакты', contact_path, :class => 'active')
							= link_to('Цены', price_path, :class => 'active')
							= link_to('Вопрос-ответ', index_questions_path(1), :class => 'active')
							= link_to('Статьи', news_path, :class => 'active')
							= link_to('RoR для создания соц...', book_path, :class => 'active')
							=# %a#showButton вход
							=# link_to_function "Show me the Magic!" do |page|
							-# page.replace_html :nav, 'dsfsdf'
							-# page.select("#nav a").each do |element|
							-# element.visual_effect :highlight
					%h2 Свежие статьи
					%ul
						- last_news.each do |n|
							%li
								= link_to(n.title, new_show_path(n.id), :class=>'active')
				.clearer
					%span
				.footer
					%h4
						Недорогой качественный и продуманный сайт в Воронеже:
						= link_to('www.юлиансайт.рф', { :controller => 'homes', :action => 'index' }, :class => 'active', :style => "color: gray;")
				.clearer
					%span